GET http://localhost:3000/healthcheck

###

POST http://localhost:3000/roles
Content-Type: application/json

{
  "users": ["maakep", "baadep", "noobslayer", "godgamer", "dragonperson_xx"]
}


###

POST http://localhost:3000/role
Content-Type: application/json

{
  "user": "bestplayer2",
  "roles": ["1", "fill", "fill", "fill", "3"],
  "userId": "<@52534543>"
}


###

GET http://localhost:3000/id/bestplayer2

###

DELETE http://localhost:3000/baadep
Content-Type: application/json


###