GET http://localhost:3000/healthcheck

###

POST http://localhost:3000/roles
Content-Type: application/json

{
  "users": ["maakep", "baadep", "noobslayer", "godgamer", "dragonperson_xx"]
}


###

POST http://localhost:3000/role
Content-Type: application/json

{
  "user": "baadep",
  "roles": ["1", "fill", "fill", "fill", "3"]
}


###